name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Run Tests and Generate Coverage
        run: npm test -- --coverage

      - name: Debugging Output
        run: |
          echo "Debugging Information:"
          echo "Current Directory: $(pwd)"
          echo "List of Files and Directories: $(ls -a)"
          # Add more echo statements or logging commands as needed

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ github.token }}
          file: coverage/lcov.info

      - name: Report to Coveralls
        run: npm run coveralls
